### ISSUE TITLE
Should this repo contain duffle.json test data?

### ISSUE THREAD

**Issue by radu-matei** [deislabs/test-bundles#1]
As we're adding common test data to this repo, I have a question about having Duffle specific test data in this repo.

Here are some arguments:

- PRO: as Duffle is the reference implementation for CNAB, and other clients might want to support building bundles using the same Duffle format, this provides an easy way to validate the client is building the bundles according to Duffle. 

- AGAINST: as this would be a CNAB specific test data repo, it should not contain any opinionated way of building bundles, as clients can come up with their specific format for the build manifest.

Thoughts?

**Comment by michelleN** [comment]
I personally think this should be CNAB specific and not contain anything about duffle or any other tooling. The goal is to test bundle manifests and that is the only thing that should live here imo.

**Comment by garethr** [comment]
I'm against this I think. Ultimately Duffle conflates a few things, mainly because that's the accepted style in Go. It's both the reference implementation for the spec (ie. a library) AND a tool in it's own right. The `duffle.toml` file is definitely part of the latter in my opinion.

If other tools want to use the `duffle.toml` file for configuration it should ideally be part of the spec, not just an implementation detail of Duffle. But I don't think it's required at the spec level.

The spec is unopinionated about build. Clients don't need to implement any build functionality at all. Adding a `duffle.toml` file doesn't just bring the config file, but an opinionated `cnab/build` directory as well.

**Comment by radu-matei** [comment]
Thanks, everyone!
As discussed, there will not be any duffle build files in this repo.

Closing.
